export const fr = {
  app: {
    loading: 'Préparation de l’arsenal',
    unit: 'unité',
    units_one: '{{count}} unité',
    units_other: '{{count}} unités',
    model_one: '{{count}} figurine',
    model_other: '{{count}} figurines',
    sourceUnavailable: 'Français partiel : tout nom, règle ou profil non couvert par une source officielle est affiché en anglais.',
    unknown: 'Non renseigné',
    none: 'Aucun'
  },
  action: {
    add: 'Ajouter', remove: 'Retirer', details: 'Détails', close: 'Fermer', reset: 'Réinitialiser',
    save: 'Enregistrer', export: 'Exporter v1', print: 'Imprimer', import: 'Importer',
    showCatalog: 'Afficher le catalogue', collapseCatalog: 'Réduire le catalogue',
    newList: 'Nouvelle liste', loadMore: 'Afficher 60 unités de plus',
    updateDatabase: 'Mettre à jour la base', importDatabase: 'Importer une base JSON',
    importList: 'Importer une liste v1', importInventory: 'Importer un inventaire CSV',
    addToList: 'Ajouter à la liste'
  },
  navigation: { language: 'Langue', french: 'Français', english: 'English' },
  rules: { open: 'Règles', unavailable: 'Référence indisponible' },
  library: {
    eyebrow: 'BIBLIOTHÈQUE', title: 'Unités disponibles', results_one: '{{count}} résultat', results_other: '{{count}} résultats',
    search: 'Rechercher une unité, un mot-clé…', allRoles: 'Tous les rôles', maximumCost: 'Coût max', favorites: 'Favoris',
    inStock: 'En stock', stockHint: 'Chargez un inventaire compatible pour filtrer le stock.',
    favorite: 'Favori {{name}}', composition: 'Composition', from: 'à partir de', unitImage: 'Visuel de {{name}}', imageUnavailable: 'Visuel indisponible pour {{name}}',
    freeStock: 'Stock libre : {{real}} réel · {{proxy}} proxy', inventoryUnlisted: 'Inventaire non renseigné',
    allied: 'Allié · {{source}}', advanced: 'Filtres avancés', active_one: '{{count}} actif', active_other: '{{count}} actifs',
    unitStats: 'Caractéristiques de l’unité', unitStatsHelp: 'Au moins un profil doit remplir toutes les conditions choisies.',
    weaponStats: 'Caractéristiques d’une arme', weaponStatsHelp: 'Une même arme doit remplir toutes les conditions choisies.',
    randomValues: 'Les valeurs aléatoires (D6, 2D6…) sont comparées avec leur maximum possible.'
  },
  profile: { movement: 'Mouvement', toughness: 'Endurance', save: 'Sauvegarde', wounds: 'Points de vie', leadership: 'Commandement', objectiveControl: 'Contrôle d’objectif', model: 'Figurine' },
  weapons: { weapons: 'Armes', weapon: 'Arme', range: 'Portée', abilities: 'Aptitudes', ranged: 'Tir', melee: 'CàC', profiles: 'Profils d’armes', unitProfiles: 'Profils d’armes de l’unité' },
  analysis: {
    title: 'Analyse de liste', subtitle: 'Dégâts, mobilité, résistance et contrôle', offense: 'Puissance offensive',
    offenseHelp: 'Dégâts moyens non sauvegardés par phase, à portée.', customTarget: 'Cible personnalisée',
    include: 'Inclure dans le tableau', name: 'Nom', toughness: 'Endurance', save: 'Sauvegarde', vehicle: 'Véhicule', monster: 'Monstre',
    unit: 'Unité', total: 'Total', empty: 'Ajoutez des unités depuis la bibliothèque.', sources_one: '{{count}} source', sources_other: '{{count}} sources',
    mobility: 'Mobilité', resilience: 'Résistance', control: 'Contrôle', bestMove: 'Meilleur M', longestRange: 'Portée max.', fastUnits: 'Unités rapides',
    rapidDeployment: 'Déploiement rapide', totalWounds: 'PV totaux', toughCore: 'Noyau E ≥ 10', saveTwo: 'Svg 2+', saveThree: 'Svg 3+',
    baseOc: 'OC de base', models: 'Figurines', battleline: 'Ligne', resolvedProfiles: 'Profils résolus',
    tactical: 'Outils tactiques structurés', noTactical: 'Aucun outil structuré détecté dans les profils sélectionnés.',
    fallbackProfiles_one: '{{count}} unité à profils multiples utilise un profil de secours pour les PV et l’OC.', fallbackProfiles_other: '{{count}} unités à profils multiples utilisent un profil de secours pour les PV et l’OC.',
    assumptions: 'Hypothèses de calcul', coverage: { absent: 'Absent', fragile: 'Fragile', covered: 'Couvert', redundant: 'Redondant' },
    target: { horde: 'Horde', infantry: 'Infanterie', elite: 'Élite', vehicle: 'Monstre / Véhicule', heavy: 'Blindage lourd' },
    assumption: { statisticalAverage: 'Moyennes statistiques des dés ; cible à portée, sans couvert, invulnérable ni Insensible à la douleur.', situationalRules: 'Les règles dépendant de la position ou de la cible (Melta, Lourde, Charge, etc.) ne sont pas incluses.', textAbilities: 'Les aptitudes textuelles restent affichées comme outils tactiques et ne modifient pas les résultats.' },
    utility: { fly: 'Vol', deepStrike: 'Frappe en profondeur', scouts: 'Éclaireurs', infiltrators: 'Infiltrateurs', stealth: 'Furtivité', loneOperative: 'Opérateur Solitaire', feelNoPain: 'Insensible à la douleur', indirectFire: 'Tir indirect', torrent: 'Torrent' }
  },
  wargear: {
    title: 'Armement et équipement', size: 'Effectif de {{name}}', selected: 'Équipement retenu', withoutProfile: 'Équipement sans profil : {{equipment}}.',
    none: 'Aucun choix d’équipement pour ce type de figurine.', replaces: 'Remplace {{equipment}}', additional: 'Équipement additionnel',
    selectedCount_one: '{{selected}}/{{maximum}} choisi', selectedCount_other: '{{selected}}/{{maximum}} choisis', requires: 'Requiert : {{detachment}}', quantity: 'Quantité de {{option}}', selectedProfiles: 'Profils des armes retenues'
  },
  roster: {
    eyebrow: 'LISTE', unnamed: 'Liste sans nom', baseSize: 'Taille / coût de base', occurrence: 'occurrence {{count}}',
    enhancement: 'Amélioration', noEnhancement: 'Aucune amélioration', baseCost: 'Base {{cost}}', surcharge: '→ surcharge {{cost}}', equipment: 'Équipement {{cost}} · Amélioration {{enhancement}}',
    reserved: 'Réservées : {{real}} réelle(s) · {{proxy}} proxy', missing: 'Manque {{count}}', validation: 'Validation', errors_one: '{{count}} erreur', errors_other: '{{count}} erreurs', valid: 'Liste prête à exporter.',
    savedLists: 'Listes sauvegardées', autosave: 'La liste active et chaque modification sont enregistrées automatiquement sur cet appareil.', delete: 'Supprimer {{name}}', removeUnit: 'Retirer {{name}}', removeDetachment: 'Retirer le détachement {{name}}', selectedDetachments: 'Détachements', scenario: 'Scénario : {{scenario}}'
  },
  command: {
    eyebrow: 'COMMANDEMENT DE LISTE', title: 'Préparer la force', intro: 'Choisissez le format, la faction et le scénario, puis enregistrez ou exportez la liste.',
    name: 'Nom de la liste', active: 'Liste active', format: 'Format', faction: 'Faction', scenario: 'Scénario', guide: 'GUIDE DE SCÉNARIO',
    allowedScenarios: 'Scénarios autorisés', detachmentBudget: 'Budget de détachements', enhancementLimit: 'Limite d’améliorations',
    detachmentEyebrow: 'DÉTACHEMENTS', detachmentTitle: 'Forces de la faction', selectedInfo_one: '{{count}} sélectionné · ils déterminent les scénarios autorisés.', selectedInfo_other: '{{count}} sélectionnés · ils déterminent les scénarios autorisés.', ruleOptions: 'Règle et options', detachmentRule: 'Règle de détachement', restriction: 'Restriction : {{text}}', stratagems: 'Stratagèmes', enhancements: 'Améliorations'
  },
  scenarios: {
    'TAKE AND HOLD': { label: 'Prendre et Tenir', guide: 'Construisez une force capable de conserver plusieurs objectifs sur la durée. Privilégiez la présence, la résistance et des unités capables de reprendre le centre.' },
    'PRIORITY ASSETS': { label: 'Ressources prioritaires', guide: 'Prévoyez des unités autonomes pour défendre et contester des ressources clés, sans immobiliser toute votre puissance de frappe.' },
    DISRUPTION: { label: 'Perturbation', guide: 'Favorisez la mobilité, la pression sur les flancs et des outils capables de perturber le plan adverse à des moments décisifs.' },
    RECONNAISSANCE: { label: 'Reconnaissance', guide: 'Valorisez les unités rapides, infiltrées ou pouvant agir loin de la force principale pour couvrir le terrain et créer des options.' },
    'PURGE THE FOE': { label: 'Purger l’ennemi', guide: 'Préservez des ressources de combat capables de réaliser des échanges favorables, tout en gardant assez d’unités pour continuer à jouer les objectifs.' }
  },
  status: { integrated: 'Catalogue V11 intégré', cache: 'Base en cache local', imported: 'Base importée : {{name}}', inventoryIntegrated: 'Inventaire intégré', associations_one: '{{source}} · {{count}} association', associations_other: '{{source}} · {{count}} associations' }
  ,feedback: { loading: 'Chargement de la base intégrée…', normalizing: 'Lecture de {{name}}…', normalizationFailed: 'Le worker de normalisation a échoué.', profileWithoutCost: 'Profil sans coût', databaseUnavailable: 'La base intégrée est indisponible.', databaseLoadFailed: 'Impossible de charger la base.', loadingFailed: 'Chargement impossible', inventoryUnavailable: 'Le CSV d’inventaire intégré est indisponible.', inventoryUnavailableShort: 'Inventaire indisponible.', cacheDatabase: 'La base est chargée, mais le cache local n’a pas pu être mis à jour.', cacheInventory: 'Inventaire chargé, mais le cache local n’a pas pu être mis à jour.', saved: 'Liste enregistrée localement. Les modifications suivantes sont sauvegardées automatiquement.', saveUnavailable: 'La sauvegarde locale est indisponible dans ce navigateur. Vérifiez que le stockage du site n’est pas bloqué.', incompatibleList: 'Cette liste est incompatible avec la base chargée.', opened: 'Liste « {{name}} » ouverte.', newList: 'Nouvelle liste créée. Elle est sauvegardée automatiquement.', deleteConfirm: 'Supprimer définitivement la liste « {{name}} » ?', deleteFailed: 'La suppression n’a pas pu être enregistrée localement.', deleted: 'Liste « {{name}} » supprimée.', factionConfirm: 'Changer de faction retire les unités et détachements actuels. Continuer ?', importedDatabaseSession: 'La base importée est maintenant celle utilisée par la session.', invalidDatabase: 'Ce fichier ne peut pas être lu comme base Warforge.', inventoryReplaced: 'Inventaire local remplacé pour cette base.', invalidInventory: 'Ce fichier ne peut pas être lu comme inventaire Warforge.', invalidExport: 'Ce fichier ne correspond pas au format Warforge v1.', incompatibleExport: 'Cette liste a été exportée avec une base incompatible et ne peut pas être rapprochée automatiquement.', incompleteExport: 'Cette liste est incomplète pour la base chargée.', importAdjusted: 'Liste importée ; le scénario a été ajusté aux détachements.', importedList: 'Liste importée.', importFailed: 'Import impossible.', inventoryMissing: '{{name}} : il manque {{count}} figurine(s) dans l’inventaire.' }
} as const;

export const en = {
  rules: { open: 'Rules', unavailable: 'Reference unavailable' },
  app: { loading: 'Preparing the arsenal', unit: 'unit', units_one: '{{count}} unit', units_other: '{{count}} units', model_one: '{{count}} model', model_other: '{{count}} models', sourceUnavailable: 'Partial French: any name, rule or profile not covered by an official source is shown in English.', unknown: 'Not provided', none: 'None' },
  action: { add: 'Add', remove: 'Remove', details: 'Details', close: 'Close', reset: 'Reset', save: 'Save', export: 'Export v1', print: 'Print', import: 'Import', showCatalog: 'Show catalog', collapseCatalog: 'Collapse catalog', newList: 'New list', loadMore: 'Show 60 more units', updateDatabase: 'Update database', importDatabase: 'Import a JSON database', importList: 'Import a v1 list', importInventory: 'Import an inventory CSV', addToList: 'Add to list' },
  navigation: { language: 'Language', french: 'Français', english: 'English' },
  library: { eyebrow: 'LIBRARY', title: 'Available units', results_one: '{{count}} result', results_other: '{{count}} results', search: 'Search a unit, keyword…', allRoles: 'All roles', maximumCost: 'Maximum cost', favorites: 'Favorites', inStock: 'In stock', stockHint: 'Load a compatible inventory to filter by stock.', favorite: 'Favorite {{name}}', composition: 'Composition', from: 'from', unitImage: 'Image of {{name}}', imageUnavailable: 'Image unavailable for {{name}}', freeStock: 'Free stock: {{real}} real · {{proxy}} proxy', inventoryUnlisted: 'Inventory not listed', allied: 'Ally · {{source}}', advanced: 'Advanced filters', active_one: '{{count}} active', active_other: '{{count}} active', unitStats: 'Unit characteristics', unitStatsHelp: 'At least one profile must meet every selected condition.', weaponStats: 'Weapon characteristics', weaponStatsHelp: 'The same weapon must meet every selected condition.', randomValues: 'Random values (D6, 2D6…) are evaluated at their highest possible result.' },
  profile: { movement: 'Movement', toughness: 'Toughness', save: 'Save', wounds: 'Wounds', leadership: 'Leadership', objectiveControl: 'Objective Control', model: 'Model' },
  weapons: { weapons: 'Weapons', weapon: 'Weapon', range: 'Range', abilities: 'Abilities', ranged: 'Ranged', melee: 'Melee', profiles: 'Weapon profiles', unitProfiles: 'Unit weapon profiles' },
  analysis: { title: 'List analysis', subtitle: 'Damage, mobility, resilience and control', offense: 'Offensive power', offenseHelp: 'Average unsaved damage per phase, in range.', customTarget: 'Custom target', include: 'Include in table', name: 'Name', toughness: 'Toughness', save: 'Save', vehicle: 'Vehicle', monster: 'Monster', unit: 'Unit', total: 'Total', empty: 'Add units from the library.', sources_one: '{{count}} source', sources_other: '{{count}} sources', mobility: 'Mobility', resilience: 'Resilience', control: 'Control', bestMove: 'Best M', longestRange: 'Max. range', fastUnits: 'Fast units', rapidDeployment: 'Rapid deployment', totalWounds: 'Total Wounds', toughCore: 'T ≥ 10 core', saveTwo: '2+ Sv', saveThree: '3+ Sv', baseOc: 'Base OC', models: 'Models', battleline: 'Battleline', resolvedProfiles: 'Resolved profiles', tactical: 'Structured tactical tools', noTactical: 'No structured tool detected in selected profiles.', fallbackProfiles_one: '{{count}} multi-profile unit uses a fallback profile for Wounds and OC.', fallbackProfiles_other: '{{count}} multi-profile units use a fallback profile for Wounds and OC.', assumptions: 'Calculation assumptions', coverage: { absent: 'Absent', fragile: 'Fragile', covered: 'Covered', redundant: 'Redundant' }, target: { horde: 'Horde', infantry: 'Infantry', elite: 'Elite', vehicle: 'Monster / Vehicle', heavy: 'Heavy armour' }, assumption: { statisticalAverage: 'Statistical dice averages; target in range, with no cover, invulnerable save or Feel No Pain.', situationalRules: 'Rules that depend on position or target (Melta, Heavy, Charge, etc.) are not included.', textAbilities: 'Text abilities remain shown as tactical tools and do not modify the results.' }, utility: { fly: 'Fly', deepStrike: 'Deep Strike', scouts: 'Scouts', infiltrators: 'Infiltrators', stealth: 'Stealth', loneOperative: 'Lone Operative', feelNoPain: 'Feel No Pain', indirectFire: 'Indirect Fire', torrent: 'Torrent' } },
  wargear: { title: 'Wargear and equipment', size: '{{name}} model count', selected: 'Selected equipment', withoutProfile: 'Equipment without profile: {{equipment}}.', none: 'No equipment choice for this model type.', replaces: 'Replaces {{equipment}}', additional: 'Additional equipment', selectedCount_one: '{{selected}}/{{maximum}} selected', selectedCount_other: '{{selected}}/{{maximum}} selected', requires: 'Requires: {{detachment}}', quantity: 'Quantity of {{option}}', selectedProfiles: 'Selected weapon profiles' },
  roster: { eyebrow: 'LIST', unnamed: 'Unnamed list', baseSize: 'Base size / cost', occurrence: 'occurrence {{count}}', enhancement: 'Enhancement', noEnhancement: 'No enhancement', baseCost: 'Base {{cost}}', surcharge: '→ surcharge {{cost}}', equipment: 'Wargear {{cost}} · Enhancement {{enhancement}}', reserved: 'Reserved: {{real}} real · {{proxy}} proxy', missing: '{{count}} missing', validation: 'Validation', errors_one: '{{count}} error', errors_other: '{{count}} errors', valid: 'List ready to export.', savedLists: 'Saved lists', autosave: 'The active list and every change are saved automatically on this device.', delete: 'Delete {{name}}', removeUnit: 'Remove {{name}}', removeDetachment: 'Remove detachment {{name}}', selectedDetachments: 'Detachments', scenario: 'Scenario: {{scenario}}' },
  command: { eyebrow: 'LIST COMMAND', title: 'Prepare the force', intro: 'Choose the format, faction and scenario, then save or export the list.', name: 'List name', active: 'Active list', format: 'Format', faction: 'Faction', scenario: 'Scenario', guide: 'SCENARIO GUIDE', allowedScenarios: 'Allowed scenarios', detachmentBudget: 'Detachment budget', enhancementLimit: 'Enhancement limit', detachmentEyebrow: 'DETACHMENTS', detachmentTitle: 'Faction forces', selectedInfo_one: '{{count}} selected · they determine the allowed scenarios.', selectedInfo_other: '{{count}} selected · they determine the allowed scenarios.', ruleOptions: 'Rule and options', detachmentRule: 'Detachment rule', restriction: 'Restriction: {{text}}', stratagems: 'Stratagems', enhancements: 'Enhancements' },
  scenarios: { 'TAKE AND HOLD': { label: 'Take and Hold', guide: 'Build a force that can hold several objectives over time. Prioritise presence, resilience and units able to retake the centre.' }, 'PRIORITY ASSETS': { label: 'Priority Assets', guide: 'Plan autonomous units to defend and contest key resources without immobilising all your striking power.' }, DISRUPTION: { label: 'Disruption', guide: 'Prioritise mobility, pressure on flanks and tools that can disrupt the opposing plan at decisive moments.' }, RECONNAISSANCE: { label: 'Reconnaissance', guide: 'Value fast, infiltrating units or units able to act far from the main force to cover the board and create options.' }, 'PURGE THE FOE': { label: 'Purge the Foe', guide: 'Preserve combat resources able to make favourable trades while retaining enough units to keep playing the objectives.' } },
  status: { integrated: 'Integrated V11 catalog', cache: 'Local cached database', imported: 'Imported database: {{name}}', inventoryIntegrated: 'Integrated inventory', associations_one: '{{source}} · {{count}} association', associations_other: '{{source}} · {{count}} associations' },
  feedback: { loading: 'Loading integrated database…', normalizing: 'Reading {{name}}…', normalizationFailed: 'The normalization worker failed.', profileWithoutCost: 'Profile without a cost', databaseUnavailable: 'Integrated database unavailable.', databaseLoadFailed: 'Unable to load database.', loadingFailed: 'Loading failed', inventoryUnavailable: 'Integrated inventory CSV unavailable.', inventoryUnavailableShort: 'Inventory unavailable.', cacheDatabase: 'The database is loaded, but the local cache could not be updated.', cacheInventory: 'Inventory loaded, but the local cache could not be updated.', saved: 'List saved locally. Further changes are saved automatically.', saveUnavailable: 'Local saving is unavailable in this browser. Check that site storage is not blocked.', incompatibleList: 'This list is incompatible with the loaded database.', opened: 'List “{{name}}” opened.', newList: 'New list created. It is saved automatically.', deleteConfirm: 'Permanently delete “{{name}}”?', deleteFailed: 'The deletion could not be saved locally.', deleted: 'List “{{name}}” deleted.', factionConfirm: 'Changing faction removes the current units and detachments. Continue?', importedDatabaseSession: 'The imported database is now used for this session.', invalidDatabase: 'This file cannot be read as a Warforge database.', inventoryReplaced: 'Local inventory replaced for this database.', invalidInventory: 'This file cannot be read as a Warforge inventory.', invalidExport: 'This file does not match the Warforge v1 format.', incompatibleExport: 'This list was exported with an incompatible database and cannot be matched automatically.', incompleteExport: 'This list is incomplete for the loaded database.', importAdjusted: 'List imported; its scenario was adjusted to its detachments.', importedList: 'List imported.', importFailed: 'Import failed.', inventoryMissing: '{{name}}: {{count}} model(s) missing from inventory.' }
};
